"""Copy the local MoodPick Oracle schema and data to Autonomous Database.

The source connection uses the normal ``ORACLE_*`` variables. The target uses
``TARGET_ORACLE_*`` variables and an extracted Autonomous Database wallet.
The script refuses to overwrite a target schema that already contains data.
"""
from __future__ import annotations

import os

import oracledb
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

from app.db.models import Base
from app.db.oracle_client import _dsn


TABLES = [
    "USERS",
    "AUTH_SESSIONS",
    "USER_TASTE_PROFILE",
    "ITEMS",
    "INTERACTIONS",
    "ONBOARDING_SIGNALS",
    "CONVERSATION_SIGNALS",
    "MOVIES",
    "BOOKS",
]


def _required(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def _target_connect_args() -> dict[str, str]:
    wallet_dir = _required("TARGET_ORACLE_WALLET_DIR")
    return {
        "dsn": os.getenv("TARGET_ORACLE_DSN", "moodpick_low"),
        "config_dir": wallet_dir,
        "wallet_location": wallet_dir,
        "wallet_password": _required("TARGET_ORACLE_WALLET_PASSWORD"),
    }


def _create_target_user() -> None:
    admin_password = _required("TARGET_ORACLE_ADMIN_PASSWORD")
    app_user = os.getenv("TARGET_ORACLE_USER", "moodpick").upper()
    app_password = _required("TARGET_ORACLE_USER_PASSWORD")
    connect_args = _target_connect_args()

    with oracledb.connect(user="ADMIN", password=admin_password, **connect_args) as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM all_users WHERE username = :username",
                username=app_user,
            )
            if cursor.fetchone()[0] == 0:
                cursor.execute(
                    f'CREATE USER {app_user} IDENTIFIED BY "{app_password}" '
                    "DEFAULT TABLESPACE DATA QUOTA UNLIMITED ON DATA"
                )
            else:
                cursor.execute(f'ALTER USER {app_user} IDENTIFIED BY "{app_password}"')
            cursor.execute(
                f"GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, "
                f"CREATE TRIGGER, CREATE VIEW TO {app_user}"
            )


def _target_engine():
    return create_engine(
        URL.create(
            "oracle+oracledb",
            username=os.getenv("TARGET_ORACLE_USER", "moodpick"),
            password=_required("TARGET_ORACLE_USER_PASSWORD"),
        ),
        connect_args=_target_connect_args(),
    )


def _plain_value(value):
    if isinstance(value, oracledb.LOB):
        return value.read()
    return value


def migrate() -> dict[str, int]:
    _create_target_user()
    engine = _target_engine()
    Base.metadata.create_all(engine)

    with engine.connect() as target:
        existing_rows = sum(
            target.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar_one()
            for table in TABLES
        )
    if existing_rows:
        raise RuntimeError("Target schema already contains data; migration aborted")

    source = oracledb.connect(
        user=_required("ORACLE_USER"),
        password=_required("ORACLE_PASSWORD"),
        dsn=_dsn(),
    )
    counts: dict[str, int] = {}
    try:
        with engine.begin() as target:
            for table in TABLES:
                with source.cursor() as cursor:
                    cursor.execute(f"SELECT * FROM {table}")
                    columns = [description[0] for description in cursor.description]
                    rows = [tuple(_plain_value(value) for value in row) for row in cursor]

                if rows:
                    column_sql = ", ".join(columns)
                    bind_sql = ", ".join(f":{index + 1}" for index in range(len(columns)))
                    target.exec_driver_sql(
                        f"INSERT INTO {table} ({column_sql}) VALUES ({bind_sql})",
                        rows,
                    )
                counts[table] = len(rows)

            target.execute(text("CREATE UNIQUE INDEX UQ_USERS_EMAIL_CI ON USERS (LOWER(EMAIL))"))
            for table in TABLES:
                target.execute(
                    text(
                        f"ALTER TABLE {table} MODIFY ID GENERATED BY DEFAULT "
                        "AS IDENTITY (START WITH LIMIT VALUE)"
                    )
                )
    finally:
        source.close()
        engine.dispose()

    return counts


if __name__ == "__main__":
    for table_name, row_count in migrate().items():
        print(f"{table_name}={row_count}")
